export const OBSERVACOES_GRADE = [
  "Obs.1: O DIA TURMA É RESPONSÁVEL POR VERIFICIAR COM OS INTRUTORES OU VER JUNTO A SETEB SE SERÃO NECESSÁRIOS RECURSOS OU MATERIAIS PARA AS INSTRUÇÕES.",
  "Obs.2: O DIA TURMA É RESPONSÁVEL POR CONFERIR NO DIA ANTERIOR O HORÁRIO DE DESLOCAMENTO E O MATERIAL NECESSÁRIO PARA INSTRUÇÃO FORA DA UNIDADE",
];
